//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATrackingDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.AdditionalTools = new HashSet<AdditionalTool>();
            this.DataSources = new HashSet<DataSource>();
            this.DeploymentServers = new HashSet<DeploymentServer>();
            this.DevelopmentLanguages = new HashSet<DevelopmentLanguage>();
            this.FrameworkUseds = new HashSet<FrameworkUsed>();
            this.PatternUseds = new HashSet<PatternUsed>();
            this.SkillsRequireds = new HashSet<SkillsRequired>();
            this.ApplicationMethodologies = new HashSet<ApplicationMethodology>();
        }
    
        public int ApplicationID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationEnvironment { get; set; }
        public string DevelopingCompany { get; set; }
        public string ProjectManager { get; set; }
        public string OperatingSystem { get; set; }
        public string IDE { get; set; }
        public string VersionControlTool { get; set; }
        public string VersionControlPath { get; set; }
        public string ApplicationType { get; set; }
        public string UnitTestTool { get; set; }
        public string DeployementTool { get; set; }
        public Nullable<System.DateTime> DeployedDate { get; set; }
        public string OutsideApplication { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<AdditionalTool> AdditionalTools { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<DataSource> DataSources { get; set; }
        public virtual ICollection<DeploymentServer> DeploymentServers { get; set; }
        public virtual ICollection<DevelopmentLanguage> DevelopmentLanguages { get; set; }
        public virtual ICollection<FrameworkUsed> FrameworkUseds { get; set; }
        public virtual ICollection<PatternUsed> PatternUseds { get; set; }
        public virtual ICollection<SkillsRequired> SkillsRequireds { get; set; }
        public virtual ICollection<ApplicationMethodology> ApplicationMethodologies { get; set; }
    }
}
