//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATrackingDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationEnvironment
    {
        public ApplicationEnvironment()
        {
            this.DataSources = new HashSet<DataSource>();
            this.DeploymentServers = new HashSet<DeploymentServer>();
        }
    
        public int ApplicationEnvironmentID { get; set; }
        public string ApplicationEnvironmentName { get; set; }
    
        public virtual ICollection<DataSource> DataSources { get; set; }
        public virtual ICollection<DeploymentServer> DeploymentServers { get; set; }
    }
}
