//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATrackingDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnit
    {
        public int BusinessUnitID { get; set; }
        public int OrganizationID { get; set; }
        public string BusinessUnitName { get; set; }
        public string Comment { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
