//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATrackingDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdditionalTool> AdditionalTools { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<ApplicationEnvironment> ApplicationEnvironments { get; set; }
        public DbSet<BusinessUnit> BusinessUnits { get; set; }
        public DbSet<DataSource> DataSources { get; set; }
        public DbSet<DeploymentServer> DeploymentServers { get; set; }
        public DbSet<DevelopmentLanguage> DevelopmentLanguages { get; set; }
        public DbSet<FrameworkUsed> FrameworkUseds { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<PatternUsed> PatternUseds { get; set; }
        public DbSet<SkillsRequired> SkillsRequireds { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<ApplicationMethodology> ApplicationMethodologies { get; set; }
        public DbSet<vwDataSource> vwDataSources { get; set; }
        public DbSet<vwAllLanguage> vwAllLanguages { get; set; }
        public DbSet<vwAllMethodology> vwAllMethodologies { get; set; }
        public DbSet<vwAllDataSource> vwAllDataSources { get; set; }
        public DbSet<vwAllDeploymentServer> vwAllDeploymentServers { get; set; }
        public DbSet<vwDeploymentServer> vwDeploymentServers { get; set; }
        public DbSet<vwAllAddTool> vwAllAddTools { get; set; }
        public DbSet<vwAllFramework> vwAllFrameworks { get; set; }
        public DbSet<vwAllSkill> vwAllSkills { get; set; }
    }
}
