//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATrackingDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDeploymentServer
    {
        public int DeploymentServerID { get; set; }
        public int ApplicationID { get; set; }
        public int ApplicationEnvironmentID { get; set; }
        public string DeploymentServerName { get; set; }
        public string ApplicationEnvironmentName { get; set; }
    }
}
